// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package webapp

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>scss files graphing</title><link rel=\"stylesheet\" type=\"text/css\" href=\"static/output.css\"></head><body class=\"p-8\"><h1 class=\"text-3xl font-mono font-semibold\">How do the files relate to each other?</h1><div class=\"w-full h-5/6 flex\"><div id=\"graphContainer\" class=\"w-2/3 overflow-scroll h-full\"><div id=\"graph\"></div></div><div class=\"w-1/3 h-full\"><div class=\"p-4\"><h2 class=\"text-xl font-mono font-semibold\">File details</h2><h3 class=\"text-lg font-mono font-semibold\">Total Number of Files: <span id=\"totalFiles\"></span></h3><h4 class=\"text-lg font-mono\">SCSS Files: <span id=\"scssFiles\"></span></h4><h4 class=\"text-lg font-mono\">JSX? Files: <span id=\"jsFiles\"></span></h4><h3 class=\"text-lg font-mono font-semibold\">Total Number of Imports: <span id=\"imports\"></span></h3><h4 class=\"text-lg font-mono \">Imports from SCSS Files: <span id=\"scssImports\"></span></h4><h4 class=\"text-lg font-mono \">Imports from JSX Files: <span id=\"jsImports\"></span></h4><div id=\"fileDetails\"></div></div></div></div></body><script src=\"https://cdn.jsdelivr.net/npm/d3@7\"></script><script src=\"static/index.js\"></script></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
